### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jessear** [iceCola7/WanAndroid#40]
Process: com.cxz.wanandroid, PID: 665
    java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/app/TinkerApplication; or its super classes (declaration of 'com.tencent.tinker.loader.app.TinkerApplication' appears in /data/app/com.cxz.wanandroid-wkWwEkOekEfI_2O1qkI9rA==/base.apk)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.<init>(BUGLY:44)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at android.support.v4.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1202)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1258)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6793)
        at android.app.ActivityThread.access$1500(ActivityThread.java:255)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7752)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by sheilazxx** [comment]
把tinker-support.gradle文件中的`enableProxyApplication = true `改为`enableProxyApplication = false`

**Comment by iceCola7** [comment]
谢谢反馈~
主要是因为升级了tinker的版本，所以才导致启动报错了，现在已经改好了~
