### ISSUE TITLE
启动报错了

### ISSUE THREAD

**Issue by liangjiajiajia** [iceCola7/WanAndroid#41]
`I/QarthLog: [PatchStore] createDisableExceptionQarthFile
E/QarthLog: [PatchStore] current thread application info is null
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.cxz.wanandroid#10229#256
    need clear apicache,because volumes changed,oldCnt=0 newCnt=1
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cxz.wanandroid, PID: 11702
    java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/app/TinkerApplication; or its super classes (declaration of 'com.tencent.tinker.loader.app.TinkerApplication' appears in /data/app/com.cxz.wanandroid-YzSx-U7cjmZFnh-SL0u4qA==/base.apk)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.<init>(BUGLY:44)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at android.support.v4.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1167)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7322)
        at android.app.ActivityThread.access$2400(ActivityThread.java:308)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
I/Process: Sending signal. PID: 11702 SIG: 9`

**Comment by ssj2020** [comment]
直接删除bugly有关代码即可

**Comment by iceCola7** [comment]
谢谢反馈~
主要是因为升级了tinker的版本，所以才导致启动报错了，现在已经改好了~
