### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Reginer** [iceCola7/WanAndroid#46]
更新之后点开文章详情直接闪退了，看看你那能不能用

**Comment by Reginer** [comment]
```
Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cxz.wanandroid/com.cxz.wanandroid.ui.activity.ContentActivity}: android.view.InflateException: Binary XML file line #2 in com.cxz.wanandroid:layout/activity_content: Binary XML file line #2 in com.cxz.wanandroid:layout/activity_content: Error inflating class com.cxz.wanandroid.widget.WebContainer
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4028)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4215)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2580)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8622)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: android.view.InflateException: Binary XML file line #2 in com.cxz.wanandroid:layout/activity_content: Binary XML file line #2 in com.cxz.wanandroid:layout/activity_content: Error inflating class com.cxz.wanandroid.widget.WebContainer
     Caused by: android.view.InflateException: Binary XML file line #2 in com.cxz.wanandroid:layout/activity_content: Error inflating class com.cxz.wanandroid.widget.WebContainer
     Caused by: java.lang.NoSuchMethodException: com.cxz.wanandroid.widget.WebContainer.<init> [class android.content.Context, interface android.util.AttributeSet]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at android.view.LayoutInflater.createView(LayoutInflater.java:834)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:669)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
        at com.cxz.wanandroid.base.BaseActivity.onCreate(BaseActivity.kt:3)
        at com.cxz.wanandroid.base.BaseMvpSwipeBackActivity.onCreate(BaseMvpSwipeBackActivity.kt:1)
        at android.app.Activity.performCreate(Activity.java:8201)
        at android.app.Activity.performCreate(Activity.java:8189)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4001)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4215)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2580)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8622)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by iceCola7** [comment]
谢谢反馈，正在查明原因。。。

**Comment by iceCola7** [comment]
已经改好了，可以在更新体验~~
